package com.owen.wms.lekani.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-27T13:40:51.261+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "Lekani_Standard_WebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface LekaniStandardWebServiceSoap {

    /**
     * 根据类目ID获取类目信息
     */
    @WebResult(name = "GET_CATINFHOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GET_CATINFHO", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETCATINFHO")
    @WebMethod(operationName = "GET_CATINFHO", action = "http://tempuri.org/GET_CATINFHO")
    @ResponseWrapper(localName = "GET_CATINFHOResponse", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETCATINFHOResponse")
    public java.lang.String getCATINFHO(
        @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(name = "CatID", targetNamespace = "http://tempuri.org/")
        int catID
    );

    /**
     * 获取产品列表（中文）
     */
    @WebResult(name = "GET_PRODUCTLISTResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GET_PRODUCTLIST", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETPRODUCTLIST")
    @WebMethod(operationName = "GET_PRODUCTLIST", action = "http://tempuri.org/GET_PRODUCTLIST")
    @ResponseWrapper(localName = "GET_PRODUCTLISTResponse", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETPRODUCTLISTResponse")
    public java.lang.String getPRODUCTLIST(
        @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(name = "PageIndex", targetNamespace = "http://tempuri.org/")
        int pageIndex,
        @WebParam(name = "CatID", targetNamespace = "http://tempuri.org/")
        int catID,
        @WebParam(name = "BrandID", targetNamespace = "http://tempuri.org/")
        int brandID,
        @WebParam(name = "ShopBeginTime", targetNamespace = "http://tempuri.org/")
        java.lang.String shopBeginTime,
        @WebParam(name = "ShopEndTime", targetNamespace = "http://tempuri.org/")
        java.lang.String shopEndTime,
        @WebParam(name = "SKUS", targetNamespace = "http://tempuri.org/")
        java.lang.String skus
    );

    /**
     * TP登陆
     */
    @WebResult(name = "TPLOGINResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TPLOGIN", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.TPLOGIN")
    @WebMethod(operationName = "TPLOGIN", action = "http://tempuri.org/TPLOGIN")
    @ResponseWrapper(localName = "TPLOGINResponse", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.TPLOGINResponse")
    public java.lang.String tplogin(
        @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
        java.lang.String userID,
        @WebParam(name = "PWD", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    @WebResult(name = "GET_SUITResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GET_SUIT", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETSUIT")
    @WebMethod(operationName = "GET_SUIT", action = "http://tempuri.org/GET_SUIT")
    @ResponseWrapper(localName = "GET_SUITResponse", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETSUITResponse")
    public java.lang.String getSUIT(
        @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key
    );

    /**
     * 获取产品库存
     */
    @WebResult(name = "Get_STOCKResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_STOCK", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GetSTOCK")
    @WebMethod(operationName = "Get_STOCK", action = "http://tempuri.org/Get_STOCK")
    @ResponseWrapper(localName = "Get_STOCKResponse", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GetSTOCKResponse")
    public java.lang.String getSTOCK(
        @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(name = "SKU", targetNamespace = "http://tempuri.org/")
        java.lang.String sku
    );

    /**
     * 根据品牌ID获取品牌信息
     */
    @WebResult(name = "GET_BRANDINFOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GET_BRANDINFO", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETBRANDINFO")
    @WebMethod(operationName = "GET_BRANDINFO", action = "http://tempuri.org/GET_BRANDINFO")
    @ResponseWrapper(localName = "GET_BRANDINFOResponse", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETBRANDINFOResponse")
    public java.lang.String getBRANDINFO(
        @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(name = "BrandID", targetNamespace = "http://tempuri.org/")
        int brandID
    );

    /**
     * 根据ProductID或SKU获取中文产品信息
     */
    @WebResult(name = "GET_PRODUCTINFOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GET_PRODUCTINFO", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETPRODUCTINFO")
    @WebMethod(operationName = "GET_PRODUCTINFO", action = "http://tempuri.org/GET_PRODUCTINFO")
    @ResponseWrapper(localName = "GET_PRODUCTINFOResponse", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETPRODUCTINFOResponse")
    public java.lang.String getPRODUCTINFO(
        @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(name = "ProdcutID", targetNamespace = "http://tempuri.org/")
        int prodcutID,
        @WebParam(name = "Sku", targetNamespace = "http://tempuri.org/")
        java.lang.String sku
    );

    /**
     * 获取品牌列表
     */
    @WebResult(name = "GET_BRANDLISTResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GET_BRANDLIST", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETBRANDLIST")
    @WebMethod(operationName = "GET_BRANDLIST", action = "http://tempuri.org/GET_BRANDLIST")
    @ResponseWrapper(localName = "GET_BRANDLISTResponse", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETBRANDLISTResponse")
    public java.lang.String getBRANDLIST(
        @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key
    );

    /**
     * 获取属性列表
     */
    @WebResult(name = "GET_ATTRIBUTESINFOLISTResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GET_ATTRIBUTESINFOLIST", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETATTRIBUTESINFOLIST")
    @WebMethod(operationName = "GET_ATTRIBUTESINFOLIST", action = "http://tempuri.org/GET_ATTRIBUTESINFOLIST")
    @ResponseWrapper(localName = "GET_ATTRIBUTESINFOLISTResponse", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETATTRIBUTESINFOLISTResponse")
    public java.lang.String getATTRIBUTESINFOLIST(
        @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key
    );

    /**
     * 获取类目分类列表
     */
    @WebResult(name = "GET_CATLISTResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GET_CATLIST", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETCATLIST")
    @WebMethod(operationName = "GET_CATLIST", action = "http://tempuri.org/GET_CATLIST")
    @ResponseWrapper(localName = "GET_CATLISTResponse", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETCATLISTResponse")
    public java.lang.String getCATLIST(
        @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key
    );

    /**
     * TP产品列表
     */
    @WebResult(name = "TPGET_EBAYPRODUCTLISTResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TPGET_EBAYPRODUCTLIST", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.TPGETEBAYPRODUCTLIST")
    @WebMethod(operationName = "TPGET_EBAYPRODUCTLIST", action = "http://tempuri.org/TPGET_EBAYPRODUCTLIST")
    @ResponseWrapper(localName = "TPGET_EBAYPRODUCTLISTResponse", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.TPGETEBAYPRODUCTLISTResponse")
    public java.lang.String tpgetEBAYPRODUCTLIST(
        @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
        java.lang.String userID,
        @WebParam(name = "Token", targetNamespace = "http://tempuri.org/")
        java.lang.String token
    );

    /**
     * 获取莱卡尼非现货销售产品（包括定做产品，售完即止等产品）
     */
    @WebResult(name = "GET_NO_SPOTSALESResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GET_NO_SPOTSALES", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETNOSPOTSALES")
    @WebMethod(operationName = "GET_NO_SPOTSALES", action = "http://tempuri.org/GET_NO_SPOTSALES")
    @ResponseWrapper(localName = "GET_NO_SPOTSALESResponse", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETNOSPOTSALESResponse")
    public java.lang.String getNOSPOTSALES(
        @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(name = "SKUS", targetNamespace = "http://tempuri.org/")
        java.lang.String skus
    );

    /**
     * 根据SKU判断此商品是否下架
     */
    @WebResult(name = "Get_ISOFFSHELVESResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_ISOFFSHELVES", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GetISOFFSHELVES")
    @WebMethod(operationName = "Get_ISOFFSHELVES", action = "http://tempuri.org/Get_ISOFFSHELVES")
    @ResponseWrapper(localName = "Get_ISOFFSHELVESResponse", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GetISOFFSHELVESResponse")
    public java.lang.String getISOFFSHELVES(
        @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(name = "SKU", targetNamespace = "http://tempuri.org/")
        java.lang.String sku
    );

    /**
     * 获取产品列表（英文）
     */
    @WebResult(name = "GET_PRODUCTENLISTResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GET_PRODUCTENLIST", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETPRODUCTENLIST")
    @WebMethod(operationName = "GET_PRODUCTENLIST", action = "http://tempuri.org/GET_PRODUCTENLIST")
    @ResponseWrapper(localName = "GET_PRODUCTENLISTResponse", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETPRODUCTENLISTResponse")
    public java.lang.String getPRODUCTENLIST(
        @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(name = "PageIndex", targetNamespace = "http://tempuri.org/")
        int pageIndex,
        @WebParam(name = "CatID", targetNamespace = "http://tempuri.org/")
        int catID,
        @WebParam(name = "BrandID", targetNamespace = "http://tempuri.org/")
        int brandID,
        @WebParam(name = "ShopBeginTime", targetNamespace = "http://tempuri.org/")
        java.lang.String shopBeginTime,
        @WebParam(name = "ShopEndTime", targetNamespace = "http://tempuri.org/")
        java.lang.String shopEndTime,
        @WebParam(name = "SKUS", targetNamespace = "http://tempuri.org/")
        java.lang.String skus
    );

    /**
     * 根据ProductID或SKU获取中英文产品信息
     */
    @WebResult(name = "GET_PRODUCTENINFOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GET_PRODUCTENINFO", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETPRODUCTENINFO")
    @WebMethod(operationName = "GET_PRODUCTENINFO", action = "http://tempuri.org/GET_PRODUCTENINFO")
    @ResponseWrapper(localName = "GET_PRODUCTENINFOResponse", targetNamespace = "http://tempuri.org/", className = "com.owen.wms.lekani.wsdl.GETPRODUCTENINFOResponse")
    public java.lang.String getPRODUCTENINFO(
        @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(name = "ProdcutID", targetNamespace = "http://tempuri.org/")
        int prodcutID,
        @WebParam(name = "Sku", targetNamespace = "http://tempuri.org/")
        java.lang.String sku
    );
}
