package com.owen.wms.lekani.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-27T13:40:51.277+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "Lekani_Standard_WebServiceHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LekaniStandardWebServiceHttpGet {

    /**
     * 根据类目ID获取类目信息
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GET_CATINFHO")
    public java.lang.String getCATINFHO(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(partName = "CatID", name = "CatID", targetNamespace = "http://tempuri.org/")
        java.lang.String catID
    );

    /**
     * 获取产品列表（中文）
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GET_PRODUCTLIST")
    public java.lang.String getPRODUCTLIST(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(partName = "PageIndex", name = "PageIndex", targetNamespace = "http://tempuri.org/")
        java.lang.String pageIndex,
        @WebParam(partName = "CatID", name = "CatID", targetNamespace = "http://tempuri.org/")
        java.lang.String catID,
        @WebParam(partName = "BrandID", name = "BrandID", targetNamespace = "http://tempuri.org/")
        java.lang.String brandID,
        @WebParam(partName = "ShopBeginTime", name = "ShopBeginTime", targetNamespace = "http://tempuri.org/")
        java.lang.String shopBeginTime,
        @WebParam(partName = "ShopEndTime", name = "ShopEndTime", targetNamespace = "http://tempuri.org/")
        java.lang.String shopEndTime,
        @WebParam(partName = "SKUS", name = "SKUS", targetNamespace = "http://tempuri.org/")
        java.lang.String skus
    );

    /**
     * TP登陆
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "TPLOGIN")
    public java.lang.String tplogin(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(partName = "UserID", name = "UserID", targetNamespace = "http://tempuri.org/")
        java.lang.String userID,
        @WebParam(partName = "PWD", name = "PWD", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GET_SUIT")
    public java.lang.String getSUIT(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key
    );

    /**
     * 获取产品库存
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "Get_STOCK")
    public java.lang.String getSTOCK(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(partName = "SKU", name = "SKU", targetNamespace = "http://tempuri.org/")
        java.lang.String sku
    );

    /**
     * 根据品牌ID获取品牌信息
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GET_BRANDINFO")
    public java.lang.String getBRANDINFO(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(partName = "BrandID", name = "BrandID", targetNamespace = "http://tempuri.org/")
        java.lang.String brandID
    );

    /**
     * 根据ProductID或SKU获取中文产品信息
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GET_PRODUCTINFO")
    public java.lang.String getPRODUCTINFO(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(partName = "ProdcutID", name = "ProdcutID", targetNamespace = "http://tempuri.org/")
        java.lang.String prodcutID,
        @WebParam(partName = "Sku", name = "Sku", targetNamespace = "http://tempuri.org/")
        java.lang.String sku
    );

    /**
     * 获取品牌列表
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GET_BRANDLIST")
    public java.lang.String getBRANDLIST(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key
    );

    /**
     * 获取属性列表
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GET_ATTRIBUTESINFOLIST")
    public java.lang.String getATTRIBUTESINFOLIST(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key
    );

    /**
     * 获取类目分类列表
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GET_CATLIST")
    public java.lang.String getCATLIST(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key
    );

    /**
     * TP产品列表
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "TPGET_EBAYPRODUCTLIST")
    public java.lang.String tpgetEBAYPRODUCTLIST(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(partName = "UserID", name = "UserID", targetNamespace = "http://tempuri.org/")
        java.lang.String userID,
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://tempuri.org/")
        java.lang.String token
    );

    /**
     * 获取莱卡尼非现货销售产品（包括定做产品，售完即止等产品）
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GET_NO_SPOTSALES")
    public java.lang.String getNOSPOTSALES(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(partName = "SKUS", name = "SKUS", targetNamespace = "http://tempuri.org/")
        java.lang.String skus
    );

    /**
     * 根据SKU判断此商品是否下架
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "Get_ISOFFSHELVES")
    public java.lang.String getISOFFSHELVES(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(partName = "SKU", name = "SKU", targetNamespace = "http://tempuri.org/")
        java.lang.String sku
    );

    /**
     * 获取产品列表（英文）
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GET_PRODUCTENLIST")
    public java.lang.String getPRODUCTENLIST(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(partName = "PageIndex", name = "PageIndex", targetNamespace = "http://tempuri.org/")
        java.lang.String pageIndex,
        @WebParam(partName = "CatID", name = "CatID", targetNamespace = "http://tempuri.org/")
        java.lang.String catID,
        @WebParam(partName = "BrandID", name = "BrandID", targetNamespace = "http://tempuri.org/")
        java.lang.String brandID,
        @WebParam(partName = "ShopBeginTime", name = "ShopBeginTime", targetNamespace = "http://tempuri.org/")
        java.lang.String shopBeginTime,
        @WebParam(partName = "ShopEndTime", name = "ShopEndTime", targetNamespace = "http://tempuri.org/")
        java.lang.String shopEndTime,
        @WebParam(partName = "SKUS", name = "SKUS", targetNamespace = "http://tempuri.org/")
        java.lang.String skus
    );

    /**
     * 根据ProductID或SKU获取中英文产品信息
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GET_PRODUCTENINFO")
    public java.lang.String getPRODUCTENINFO(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(partName = "ProdcutID", name = "ProdcutID", targetNamespace = "http://tempuri.org/")
        java.lang.String prodcutID,
        @WebParam(partName = "Sku", name = "Sku", targetNamespace = "http://tempuri.org/")
        java.lang.String sku
    );
}
