
package com.owen.wms.lekani.wsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-27T13:40:51.210+08:00
 * Generated source version: 3.1.5
 * 
 */
public final class LekaniStandardWebServiceSoap_LekaniStandardWebServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "Lekani_Standard_WebService");

    private LekaniStandardWebServiceSoap_LekaniStandardWebServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LekaniStandardWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LekaniStandardWebService ss = new LekaniStandardWebService(wsdlURL, SERVICE_NAME);
        LekaniStandardWebServiceSoap port = ss.getLekaniStandardWebServiceSoap();  
        
        {
        System.out.println("Invoking getCATINFHO...");
        java.lang.String _getCATINFHO_key = "";
        int _getCATINFHO_catID = 0;
        java.lang.String _getCATINFHO__return = port.getCATINFHO(_getCATINFHO_key, _getCATINFHO_catID);
        System.out.println("getCATINFHO.result=" + _getCATINFHO__return);


        }
        {
        System.out.println("Invoking getPRODUCTLIST...");
        java.lang.String _getPRODUCTLIST_key = "";
        int _getPRODUCTLIST_pageIndex = 0;
        int _getPRODUCTLIST_catID = 0;
        int _getPRODUCTLIST_brandID = 0;
        java.lang.String _getPRODUCTLIST_shopBeginTime = "";
        java.lang.String _getPRODUCTLIST_shopEndTime = "";
        java.lang.String _getPRODUCTLIST_skus = "";
        java.lang.String _getPRODUCTLIST__return = port.getPRODUCTLIST(_getPRODUCTLIST_key, _getPRODUCTLIST_pageIndex, _getPRODUCTLIST_catID, _getPRODUCTLIST_brandID, _getPRODUCTLIST_shopBeginTime, _getPRODUCTLIST_shopEndTime, _getPRODUCTLIST_skus);
        System.out.println("getPRODUCTLIST.result=" + _getPRODUCTLIST__return);


        }
        {
        System.out.println("Invoking tplogin...");
        java.lang.String _tplogin_key = "";
        java.lang.String _tplogin_userID = "";
        java.lang.String _tplogin_pwd = "";
        java.lang.String _tplogin__return = port.tplogin(_tplogin_key, _tplogin_userID, _tplogin_pwd);
        System.out.println("tplogin.result=" + _tplogin__return);


        }
        {
        System.out.println("Invoking getSUIT...");
        java.lang.String _getSUIT_key = "";
        java.lang.String _getSUIT__return = port.getSUIT(_getSUIT_key);
        System.out.println("getSUIT.result=" + _getSUIT__return);


        }
        {
        System.out.println("Invoking getSTOCK...");
        java.lang.String _getSTOCK_key = "";
        java.lang.String _getSTOCK_sku = "";
        java.lang.String _getSTOCK__return = port.getSTOCK(_getSTOCK_key, _getSTOCK_sku);
        System.out.println("getSTOCK.result=" + _getSTOCK__return);


        }
        {
        System.out.println("Invoking getBRANDINFO...");
        java.lang.String _getBRANDINFO_key = "";
        int _getBRANDINFO_brandID = 0;
        java.lang.String _getBRANDINFO__return = port.getBRANDINFO(_getBRANDINFO_key, _getBRANDINFO_brandID);
        System.out.println("getBRANDINFO.result=" + _getBRANDINFO__return);


        }
        {
        System.out.println("Invoking getPRODUCTINFO...");
        java.lang.String _getPRODUCTINFO_key = "";
        int _getPRODUCTINFO_prodcutID = 0;
        java.lang.String _getPRODUCTINFO_sku = "";
        java.lang.String _getPRODUCTINFO__return = port.getPRODUCTINFO(_getPRODUCTINFO_key, _getPRODUCTINFO_prodcutID, _getPRODUCTINFO_sku);
        System.out.println("getPRODUCTINFO.result=" + _getPRODUCTINFO__return);


        }
        {
        System.out.println("Invoking getBRANDLIST...");
        java.lang.String _getBRANDLIST_key = "";
        java.lang.String _getBRANDLIST__return = port.getBRANDLIST(_getBRANDLIST_key);
        System.out.println("getBRANDLIST.result=" + _getBRANDLIST__return);


        }
        {
        System.out.println("Invoking getATTRIBUTESINFOLIST...");
        java.lang.String _getATTRIBUTESINFOLIST_key = "";
        java.lang.String _getATTRIBUTESINFOLIST__return = port.getATTRIBUTESINFOLIST(_getATTRIBUTESINFOLIST_key);
        System.out.println("getATTRIBUTESINFOLIST.result=" + _getATTRIBUTESINFOLIST__return);


        }
        {
        System.out.println("Invoking getCATLIST...");
        java.lang.String _getCATLIST_key = "";
        java.lang.String _getCATLIST__return = port.getCATLIST(_getCATLIST_key);
        System.out.println("getCATLIST.result=" + _getCATLIST__return);


        }
        {
        System.out.println("Invoking tpgetEBAYPRODUCTLIST...");
        java.lang.String _tpgetEBAYPRODUCTLIST_key = "";
        java.lang.String _tpgetEBAYPRODUCTLIST_userID = "";
        java.lang.String _tpgetEBAYPRODUCTLIST_token = "";
        java.lang.String _tpgetEBAYPRODUCTLIST__return = port.tpgetEBAYPRODUCTLIST(_tpgetEBAYPRODUCTLIST_key, _tpgetEBAYPRODUCTLIST_userID, _tpgetEBAYPRODUCTLIST_token);
        System.out.println("tpgetEBAYPRODUCTLIST.result=" + _tpgetEBAYPRODUCTLIST__return);


        }
        {
        System.out.println("Invoking getNOSPOTSALES...");
        java.lang.String _getNOSPOTSALES_key = "";
        java.lang.String _getNOSPOTSALES_skus = "";
        java.lang.String _getNOSPOTSALES__return = port.getNOSPOTSALES(_getNOSPOTSALES_key, _getNOSPOTSALES_skus);
        System.out.println("getNOSPOTSALES.result=" + _getNOSPOTSALES__return);


        }
        {
        System.out.println("Invoking getISOFFSHELVES...");
        java.lang.String _getISOFFSHELVES_key = "";
        java.lang.String _getISOFFSHELVES_sku = "";
        java.lang.String _getISOFFSHELVES__return = port.getISOFFSHELVES(_getISOFFSHELVES_key, _getISOFFSHELVES_sku);
        System.out.println("getISOFFSHELVES.result=" + _getISOFFSHELVES__return);


        }
        {
        System.out.println("Invoking getPRODUCTENLIST...");
        java.lang.String _getPRODUCTENLIST_key = "";
        int _getPRODUCTENLIST_pageIndex = 0;
        int _getPRODUCTENLIST_catID = 0;
        int _getPRODUCTENLIST_brandID = 0;
        java.lang.String _getPRODUCTENLIST_shopBeginTime = "";
        java.lang.String _getPRODUCTENLIST_shopEndTime = "";
        java.lang.String _getPRODUCTENLIST_skus = "";
        java.lang.String _getPRODUCTENLIST__return = port.getPRODUCTENLIST(_getPRODUCTENLIST_key, _getPRODUCTENLIST_pageIndex, _getPRODUCTENLIST_catID, _getPRODUCTENLIST_brandID, _getPRODUCTENLIST_shopBeginTime, _getPRODUCTENLIST_shopEndTime, _getPRODUCTENLIST_skus);
        System.out.println("getPRODUCTENLIST.result=" + _getPRODUCTENLIST__return);


        }
        {
        System.out.println("Invoking getPRODUCTENINFO...");
        java.lang.String _getPRODUCTENINFO_key = "";
        int _getPRODUCTENINFO_prodcutID = 0;
        java.lang.String _getPRODUCTENINFO_sku = "";
        java.lang.String _getPRODUCTENINFO__return = port.getPRODUCTENINFO(_getPRODUCTENINFO_key, _getPRODUCTENINFO_prodcutID, _getPRODUCTENINFO_sku);
        System.out.println("getPRODUCTENINFO.result=" + _getPRODUCTENINFO__return);


        }

        System.exit(0);
    }

}
